lead_structure:
  name: "PAP_derivative"
  smiles: "O=C([*:6])Nc1cc(Nc2nccc([*:4])n2)c([*:5])cc1" # Imatinib-like scaffold
substituents: {
  1:{
  "phenyl": "[*]c1ccccc1",
  "2-pyridyl": "[*]c1ccccn1",
  "3-pyridyl": "[*]c1cccnc1",
  "4-pyridyl": "[*]c1ccncc1",
  "3-pyrrolyl": "[*]c1cc[nH]c1",
  "imidazol-1-yl": "[*]n1ccnc1"
  },

  2:{
    "ethyl": "[*]CC",
    "isopropyl": "[*]C(C)C",
    "cyclopropyl": "[*]C1CC1",
    "cyclobutyl": "[*]C1CCC1",
    "ethenyl": "[*]C=C",
    "fluoro": "[*]F",
    "chloro": "[*]Cl",
    "bromo": "[*]Br",
    "iodo": "[*]I",
    "trifluoromethyl": "[*]C(F)(F)F",
    "difluoromethyl": "[*]C(F)(F)",
    "amido": "[*]NC(=O)C",
    "carboxy": "[*]C(=O)O",
    "dimethylamino": "[*]N(C)C",
    "methylamino": "[*]NC",
    "hydroxy": "[*]O",
    "methoxy": "[*]OC",
    "amino": "[*]N",
    "cyano": "[*]C#N",
    "thioether": "[*]SC",
    "sulfoxide": "[*]S(=O)C",


    },
    3:{
    "phenyl": "[*]c1ccccc1",
    "4-methylphenyl": "[*]c1ccc(C)cc1",
    "4-fluorophenyl": "[*]c1ccc(F)cc1",
    "4-chlorophenyl": "[*]c1ccc(Cl)cc1",
    "4-cyanophenyl": "[*]c1ccc(C#N)cc1",
    "2-methoxyphenyl": "[*]c1c(OC)cccc1",
    "2-carboxyphenyl": "[*]c1c(C(=O)O)cccc1",
    "2-naphthyl": "[*]c1ccc2ccccc2c1"
  }
  }

dummy_index_pairs: [(1, 4), (2, 5), (3, 6)]

combination_csv_path: "data/generated_analogues.csv"